# Generated by Django 2.1.7 on 2019-03-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books_app', '0003_book_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_borrowed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
